In [1]:
import pandas as pd
import random
from datetime import date, timedelta

In [2]:
statuses = ['Active', 'Inactive', 'Expired', 'Cancelled', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active']
first_names = [
    'Mei', 'Liam', 'Emma', 'Noah', 'Aaliyah', 'Elijah', 'Li',
    'Lucas', 'Mia', 'Inez', 'Yasmin', 'Ethan', 'Charlotte', 'Aiden',
    'Amelia', 'James', 'Harper', 'Benjamin', 'Evelyn', 'Jacob',
    'Abigail', 'Michael', 'Jordyn', 'Daniel', 'Scarlett', 'Matthew',
    'Grace', 'Henry', 'Hassan', 'Samuel', 'Avery', 'Jack',
    'Sofia', 'Alexander', 'Madison', 'Wyatt', 'Emily', 'Travis',
    'Santiago', 'Nathan', 'Lily', 'Omari', 'Nora', 'David',
    'Ella', 'Jasper', 'Owen', 'Suki', 'Caleb', 'Nikolai',
    'Leo', 'Jasmine', 'Jordan', 'Zoe', 'Ryan', 'Penelope',
    'Gavin', 'Luna', 'Eli', 'Riley', 'Isaiah', 'Samantha',
    'Dylan', 'Victoria', 'Hunter', 'Lydia', 'Timothy', 'Stephanie', 'Dao'
]

last_names = [
    'Smith', 'Johnson', 'Brown', 'Taylor', 'Garcia', 'Yamamoto',
    'Jackson', 'White', 'Harris', 'Giordano', 'Thompson', 'Garcia',
    'Martinez', 'Sharma', 'Clark', 'Rodriguez', 'Dimitrov', 'Lee',
    'Walker', 'Hall', 'Kim', 'Lopez', 'King', 'Wright', 'El-Sayed',
    'Torres', 'Nguyen', 'Hill', 'Flores', 'Green', 'Adams',
    'Nelson', 'Carter', 'Hwang', 'Perez', 'Roberts', 'Turner',
    'Phillips', 'Singh', 'Parker', 'Ibrahim', 'Edwards', 'Collins',
    'Stewart', 'Sanchez', 'Morris', 'Wang', 'Reed', 'Cook',
    'Morgan', 'Bell', 'Murphy', 'Bailey', 'Rivera', 'Cooper',
    'Richardson', 'Cox', 'Patel', 'Ward', 'Torres', 'Baba',
    'Gray', 'Kumar', 'Cheng', 'Brooks', 'Kelly', 'Zhang', 'Iuka',
    'Heart'
]

addresses = [
    '39 Del Monte Avenue, Rolling Meadows, IL 60008', '557 NW. Ohio Ave., Sun City, AZ 85351', '9358 Shady Street, Woburn, MA 01801',
    '119 Corona Ave., Jamaica, NY 11432', '9318 Market Street, Lafayette, IN 47905', '948 Dogwood Dr., Dorchester, MA 02125',
    '796 Creekside Ave., Bristol, CT 06010', '9836 Prospect Rd., Mount Laurel, NJ 08054', '7393 Overlook Lane, East Hartford, CT 06118',
    '670 North Willow Ave., Indiana, PA 15701', '146 Mayfair Rd., Monroeville, PA 15146', '319 Orchard St., Schererville, IN 46375',
    '49 Fairfield Street, Lakewood, NJ 08701', '88 Alderwood Drive, Grandville, MI 49418', '832 Shore Rd., Pueblo, CO 81001',
    '7530 Prairie Court, Suffolk, VA 23434', '21 Carson Street, Warminster, PA 18974', '804 Hickory St., Owings Mills, MD 21117',
    '85 State St., La Vergne, TN 37086', '7807 East Beacon Ave., Apex, NC 27502', '227 South Ridge Drive, Apopka, FL 32703',
    '7791 Valley St., Ravenna, OH 44266', '635 Clark Ave., Farmington, MI 48331', '7658 Helen Dr., Garfield, NJ 07026',
    '323 Branch Street, Sulphur, LA 70663', '8 W. Golf Ave., Chaska, MN 55318', '80 Highland Avenue, Covington, GA 30014',
    '30 Shipley Road, Fort Washington, MD 20744', '7838 E. Lake View Street, Naples, FL 34116', '894 Military Court, Malvern, PA 19355',
    '9244 Hill Drive, Crown Point, IN 46307', '314 Squaw Creek Dr., Colorado Springs, CO 80911', '9032 Grand Dr., Leesburg, VA 20175',
    '8496 NW. Cobblestone St., Jamestown, NY 14701', '7897 Ivy Street, Upper Darby, PA 19082', '121 Inverness Court, Pasadena, MD 21122',
    '800 Buttonwood Street, Albany, NY 12203', '838 Morris Street, Amityville, NY 11701', '596 Bridgeton Street, Clarkston, MI 48348',
    '404 Clay St., Racine, WI 53402', '490 Rockwell St., Helena, MT 59601', '7357 Lakeshore St., Scotch Plains, NJ 07076',
    '4 College Lane, Banning, CA 92220', '7414 Mill Street, Pottstown, PA 19464', '8607 Central Street, Delaware, OH 43015',
    '2 South Cleveland Ave., Union, NJ 07083', '903 Euclid Dr., New Hyde Park, NY 11040', '492 East Purple Finch Road, Parlin, NJ 08859',
    '159 Dunbar Street, Cumming, GA 30040', '655 Howard Rd., Midlothian, VA 23112', '9876 North Homewood Rd., East Lansing, MI 48823',
    '96 Honey Creek St., Holly Springs, NC 27540', '32 Courtland Dr., Carlisle, PA 17013', '129 West St., Ocoee, FL 34761',
    '237 Glen Creek Street, Los Banos, CA 93635', '75 West Elm Dr., Elkridge, MD 21075', '845 Wild Rose St., Merrillville, IN 46410',
    '98 Beacon Lane, Wheeling, WV 26003', '8167 SE. Summit Ave., Fairmont, WV 26554', '268 Mill Pond Road, Marshalltown, IA 50158',
    '59 East Poor House Court, Lansdale, PA 19446', '8190 Carpenter St., Pearl, MS 39208', '7681 Pleasant St., Baton Rouge, LA 70806',
    '450 NE. Linda Ave., Saratoga Springs, NY 12866', '95 Elm Lane, Eastlake, OH 44095', '461 Columbia Street, Saint Albans, NY 11412',
    '338 Mayfield Lane, Williamstown, NJ 08094', '190 Glendale Court, Upper Marlboro, MD 20772', '10 Eagle Lane, Utica, NY 13501'
]

addresses2 = [
    '863 West Jackson Road, Glen Cove, NY 11542', '578 Penn Lane, Lafayette, IN 47905', '67 North Linden Street, Little Rock, AR 72209',
    '8740 N. Glenwood St., Powell, TN 37849', '68 Delaware St., Zeeland, MI 49464', '36 East Johnson Rd., Twin Falls, ID 83301',
    '84 Fordham Drive, Sunnyside, NY 11104', '4 Lilac Lane, Harrisburg, PA 17109', '44 Fawn Ave., Riverside, NJ 08075',
    '7136 Foster St., Romulus, MI 48174', '1 Prince Road, Saint Petersburg, FL 33702', '9 Prairie Ave., Coraopolis, PA 15108',
    '53 North Cedarwood Rd., Nottingham, MD 21236', '1 Pacific Street, Wilson, NC 27893', '8916 East Newport St., Irvington, NJ 07111',
    '4 Chapel Ave., Atwater, CA 95301', '9118 Livingston Road, Holly Springs, NC 27540', '836 La Sierra Rd., New Windsor, NY 12553',
    '9781 Greystone Street, Hollywood, FL 33020', '91 East Second Circle, Hastings, MN 55033', '49 Sutor Court, Montgomery Village, MD 20886',
    '385 Nichols Lane, Hernando, MS 38632', '301 Bank Ave., Simpsonville, SC 29680', '44 Wall St., Indianapolis, IN 46201',
    '9508 Victoria St., Forest Hills, NY 11375', '245 Longbranch St., Helotes, TX 78023', '915 East Annadale Ave., Boston, MA 02127',
    '8079 Oak Valley Dr., Gloucester, MA 01930', '9056 North Hickory Ave., Levittown, NY 11756', '954 Courtland Circle, New Kensington, PA 15068',
    '74 Oxford Drive, Dearborn Heights, MI 48127', '382 Euclid Rd., Austin, MN 55912', '1 Gonzales St., Janesville, WI 53546',
    '97 Valley View Rd., Collegeville, PA 19426', '550 Riverside Court, Brighton, MA 02135', '51 St Louis Street, Rahway, NJ 07065',
    '889 Blue Spring Drive, Syosset, NY 11791', '9423 Birch Hill St., Port Chester, NY 10573', '216 E. Stonybrook Ave., North Bergen, NJ 07047',
    '16 Mulberry Drive, Jersey City, NJ 07302', '7719 Cardinal St., Windsor Mill, MD 21244', '8236 W. Maple Ave., Voorhees, NJ 08043',
    '91 Wood Court, Clearwater, FL 33756', '9602 Race Street, Santa Monica, CA 90403', '381 Harvard St., Skokie, IL 60076',
    '77 N. Deerfield Ave., Little Falls, NJ 07424', '9662 West Drive, Huntersville, NC 28078', '87 Grant Drive, Princeton, NJ 08540',
    '146 East Bay Meadows St., Mount Holly, NJ 08060', '8497 Arnold Circle, Fort Lee, NJ 07024', '811 South Littleton St., Plainview, NY 11803',
    '63 Oklahoma Court, Miami, FL 33125', '617 Fawn Drive, Kingsport, TN 37660', '819 Poor House Drive, Nampa, ID 83651',
    '7793 Market Ave., Stoughton, MA 02072', '12 Rockland Lane, Livingston, NJ 07039', '189 Redwood Ave., Westfield, MA 01085',
    '758 Pin Oak St., Rockville Centre, NY 11570', '110 Airport Drive, Auburn, NY 13021', '15 Arch Road, Englishtown, NJ 07726',
    '7567 NW. Edgewood St., Unit 9, Saratoga Springs, NY 12866', '17 Wall Avenue, Victoria, TX 77904', '3 Essex Street, Tewksbury, MA 01876',
    '86 Shadow Brook Ave., Cedar Falls, IA 50613', '7373 Carriage Road, Anaheim, CA 92806', '38 Bellevue Lane, West New York, NJ 07093',
    '954 Glenridge Rd., Loveland, OH 45140', '344 Cactus Street, Snohomish, WA 98290', '8785 Glen Ridge Street, Mankato, MN 56001'
]


emails = [
    'sunsetchaser2024@gmail.com', 'cosmic_banana23@yahoo.com', 'coffeeaddict101@hotmail.com', 'quirky_pineapple55@gmail.com',
    'thunderstorm_rider@gmail.com', 'jellybean_dreamer@outlook.com', 'galaxy_explorer89@gmail.com', 'secretgarden_2023@yahoo.com',
    'vintage_voyager77@hotmail.com', 'midnight_snacker22@gmail.com', 'neon_wanderer88@gmail.com', 'ocean_wave_dancer@gmail.com',
    'frosty_penguin44@yahoo.com', 'chocolate_biscuit77@hotmail.com', 'dreamy_unicorn99@gmail.com', 'wildflower_2024@gmail.com',
    'mysterious_fox33@yahoo.com', 'playful_kangaroo11@hotmail.com', 'sunny_daydreamer55@gmail.com', 'winter_snowflake20@gmail.com',
    'funky_cactus77@yahoo.com', 'curious_gecko88@hotmail.com', 'adventurous_lizard44@gmail.com', 'electric_marmot22@gmail.com',
    'whimsical_owl99@yahoo.com', 'hidden_treasure2023@hotmail.com', 'golden_sunset_47@gmail.com', 'crafty_robot77@gmail.com',
    'tranquil_river33@yahoo.com', 'vibrant_orchid11@hotmail.com', 'pixel_artist2024@gmail.com', 'curious_cat99@gmail.com',
    'lovely_lavender22@yahoo.com', 'cosmic_turtle88@hotmail.com', 'playful_dolphin11@gmail.com', 'radiant_sunflower55@gmail.com',
    'cosmic_tornado44@yahoo.com', 'sweet_strawberry77@hotmail.com', 'gentle_breeze20@gmail.com', 'colorful_butterfly22@gmail.com',
    'midnight_wanderlust99@yahoo.com', 'adventurous_spirit2023@hotmail.com', 'joyful_raccoon44@gmail.com', 'tranquil_fox88@gmail.com',
    'breezy_island77@yahoo.com', 'playful_hummingbird11@hotmail.com', 'snowy_owl2024@gmail.com', 'cozy_fireplace55@gmail.com',
    'mystical_rainbow99@yahoo.com', 'friendly_hedgehog22@hotmail.com', 'enchanted_forest44@gmail.com', 'curious_mushroom88@gmail.com',
    'starry_night2023@yahoo.com', 'artistic_flame11@hotmail.com', 'playful_koala20@gmail.com', 'whimsical_dreamer99@gmail.com',
    'happy_hedgehog55@yahoo.com', 'thoughtful_seahorse33@hotmail.com', 'peaceful_valley2024@gmail.com', 'electric_tornado77@gmail.com',
    'clever_octopus22@yahoo.com', 'secret_snowman88@hotmail.com', 'golden_hour2023@gmail.com', 'wild_butterfly55@gmail.com',
    'joyful_explorer11@yahoo.com', 'curious_caterpillar44@hotmail.com', 'vibrant_coral99@gmail.com', 'mysterious_stars20@gmail.com',
    'dreamy_mountains2024@yahoo.com', 'colorful_parrot22@hotmail.com', 'peaceful_panda88@gmail.com', 'brave_heron11@gmail.com',
    'adventurous_spirit55@yahoo.com', 'playful_tiger33@hotmail.com', 'snowy_mountains2023@gmail.com', 'sparkling_river44@gmail.com',
    'curious_willow99@yahoo.com', 'joyful_lighthouse22@hotmail.com', 'enchanted_sunset20@gmail.com', 'cosmic_butterfly11@gmail.com',
    'radiant_horizon2024@yahoo.com', 'gentle_wave88@hotmail.com', 'sunny_garden55@gmail.com', 'whimsical_daisy33@yahoo.com',
    'mysterious_herb20@hotmail.com', 'starry_skies2023@gmail.com', 'cozy_cabin11@gmail.com', 'playful_hawk44@yahoo.com', 'joyful_daisy99@hotmail.com',
    'golden_meadow22@gmail.com', 'curious_cricket88@gmail.com', 'tranquil_jungle2024@yahoo.com', 'vibrant_horizon55@hotmail.com',
    'friendly_kite11@gmail.com', 'snowy_landscape20@gmail.com', 'radiant_sunset33@yahoo.com', 'adventurous_sky44@hotmail.com',
    'dreamy_lake99@gmail.com', 'hidden_cave2023@gmail.com', 'whimsical_river22@yahoo.com',
]

In [4]:
def generate_random_phone_number():
    area_code = random.randint(100, 999)  # Area code (3 digits)
    central_office_code = random.randint(100, 999)  # Central office code (3 digits)
    line_number = random.randint(1000, 9999)  # Line number (4 digits)
    
    phone_number = f'+1 ({area_code}) {central_office_code}-{line_number}'
    return phone_number

def generate_random_email(fname: str, lname: str):
    randInt = random.randint(0, 4)
    domains = [
        'yahoo.com',
        'gmail.com',
        'hotmail.com',
        'osu.edu',
        'buckeyemail.osu.edu',
        'ymail.com',
        'aol.com',
        'cox.net',
        'verizon.net',
        'terra.com.br',
        'hotmail.es',
        'icloud.com',
        'yahoo.co.uk',
    ]
    if randInt == 2:
        return f'{emails[random.randint(0, len(emails)-1)].split('@')[0]}@{domains[random.randint(0, len(domains)-1)]}'
    if randInt == 0:
        return f'{fname.lower()}.{lname.lower()}.{random.randint(0, 9999)}@{domains[random.randint(0, len(domains)-1)]}'
    if randInt == 1:
        return f'{fname.lower()}_{lname.lower()}{random.randint(0, 9999)}@{domains[random.randint(0, len(domains)-1)]}'
    if randInt == 3:
        return f'{fname.capitalize()}{lname.capitalize()}{random.randint(0, 9999)}@{domains[random.randint(0, len(domains)-1)]}'
    return f'{lname.capitalize()}{random.randint(0, 999999)}@{domains[random.randint(0, len(domains)-1)]}'

def generate_random_date(start: date, end: date):
    diff = end - start
    randDays = random.randint(0, diff.days)
    return start + timedelta(days=randDays)

In [6]:
##### GENERATING MEMBERS ######
members_data = {
    'MemberID': [],
    'FName': [],
    'LName': [],
    'Address': [],
    'PhoneNumber': [],
    'Email': [],
    'MembershipStartDt': [],
    'MemberStatus': []
}

for i in range(69):
    randId = random.randint(1, 99999)
    randFname = first_names[i]
    randLname = last_names[random.randrange(0, 69)]
    randAddr = addresses[random.randrange(0, 69)]
    randPhone = generate_random_phone_number()
    randEmail = generate_random_email(randFname, randLname)
    randDate = generate_random_date(date(1999, 1, 1), date(2024, 10, 29))
    randStatus = statuses[random.randint(0, len(statuses)-1)]

    members_data['MemberID'].append(randId)
    members_data['FName'].append(randFname)
    members_data['LName'].append(randLname)
    members_data['Address'].append(randAddr)
    members_data['PhoneNumber'].append(randPhone)
    members_data['Email'].append(randEmail)
    members_data['MembershipStartDt'].append(randDate)
    members_data['MemberStatus'].append(randStatus)

membersDf = pd.DataFrame(members_data)
membersDf.to_csv(r'./data_src/members.csv', index=False)

In [25]:
##### FOR GENERATING WAREHOUSE ######
warehouse_data = {
    'WarehouseID': [],
    'Address': [],
    'City': [],
    'MaxCapacity': []
}

for i in range(10):
    randAddr = addresses2[random.randint(0, len(addresses)- 1)]
    city  = randAddr.split(',')[1][1:]
    max_cap = f'{random.randrange(100, 10000, 100)} sq. ft.'

    warehouse_data['WarehouseID'].append(i + 1)
    warehouse_data['Address'].append(randAddr)
    warehouse_data['City'].append(city)
    warehouse_data['MaxCapacity'].append(max_cap)
warehouseDf = pd.DataFrame(warehouse_data)
warehouseDf.to_csv(r'./data_src/warehouse.csv', index=False)

In [33]:
manufacturer_names = [
    'GardenTogether', 'StandardNetworks', "Plumbing'r'Us", 'Water!', 'ConstructionABC', 'ElectricDance', 'Poopers!', 'Paint4Fun'
]

manufacturer_data = {
    'ManufacturerID': [],
    'Name': [],
    'Address': [],
    'City': []
}

for i, name in enumerate(manufacturer_names):
    randAddr = addresses2[random.randint(0, len(addresses)- 1)]
    city  = randAddr.split(',')[1][1:]
    manufacturer_data['ManufacturerID'].append(i + 1)
    manufacturer_data['Name'].append(name)
    manufacturer_data['Address'].append(randAddr)
    manufacturer_data['City'].append(city)

manufacturerDf = pd.DataFrame(manufacturer_data)
manufacturerDf.to_csv(r'./data_src/manufacturers.csv', index=False)